[package]
name = "actionkv"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
crc32fast = "1.4.2"
serde = {version="1.0.219", features = ["derive"]}

[[bin]]
name = "akv_mem"
path = "src/akv_mem.rs"
